### ISSUE TITLE
Request: Allow python style block comments as a function keyword argument option

### ISSUE THREAD

**Issue by AndreLouisIssa** [Anteru/sjson#2]
The SJSON present in Super Giant Games' game Hades contain block quotes in the style of python block strings

```
""" This is a multi line comment
which this module cannot parse """
```

**Comment by Anteru** [comment]
Do you have a full example file I can try? This shouldn't be too hard to add.

**Comment by Anteru** [comment]
Can you please try the speculative fix and see if that works? If so, I will prepare a new release with it.

**Comment by AndreLouisIssa** [comment]
Apologies, I was in transit trying to escape getting locked in by covid so I couldn't respond

**Comment by AndreLouisIssa** [comment]
We have a local version of your module to fix these issues
https://github.com/MagicGonads/sgg-mod-format/pull/19/commits/ae6061660c02200011929d961970943b3c5f58bf
https://github.com/MagicGonads/sgg-mod-format/pull/4/commits/0c753209765dfc33f9bd21f06afb33d1147d64ad
Can use them to see working examples

**Comment by AndreLouisIssa** [comment]
It looks like from the comparing code your speculative fix would work for the standard tripple quote case but not for the implicit quadruple quote case, don't blame you as I didn't mention that at all.

**Comment by MagicGonads** [comment]
@Anteru Yes, the speculative fix does stand-in for our current local version of the module for examples which do or do not feature tripple quotes, but I have not tested it against ones which also feature quadruple quotes (I forgot which file features that)

**Comment by AndreLouisIssa** [comment]
I tested the speculative fix, it doesn't crash but the output isn't kosher for the game, it crashes pretty violently (while the output from the local version does not crash the game)
Not exactly sure why.

**Comment by Anteru** [comment]
What is the quadruple quoted case? Looking at your changes, I don't see test cases (I'm sure they're somewhere in the repo, just don't know where :) ). If you could point me at a sample file then I can make it work, without it I'm stabbing in the dark here.

**Comment by Anteru** [comment]
Please try: 5e0c0b61c9446187649df8c728af7308dd40fc8a -- that comes with unit tests for quadruple (and while we're at it, quintuple) quoted strings.

**Comment by AndreLouisIssa** [comment]
This is what Paradigmsort/parasHadesMods said about it when I asked

"yeah, iirc the upstream only supports block quotes in the input, but it doesn't remember what was a block quote for the output
so it outputs strings with escape characters etc. in them that the game didn't understand
there were just too many differences i think for upstreaming the changes to make sense"

**Comment by AndreLouisIssa** [comment]
The tests we use are the actual game files from Hades, I don't want to distribute them wholesale

**Comment by Anteru** [comment]
If the differences are too big, then I don't really see a point in trying to support Hades specific files to be honest. Please give the commit I referenced a try, if it works, great, if not, I guess I'll revert it as I'm not willing to support something I can't test (given I don't own the game!)

**Comment by AndreLouisIssa** [comment]
I think the issue is that the multiline strings in the input become regular strings containing escape characters in the ouput

**Comment by AndreLouisIssa** [comment]
So the object in memory needs to change to remember that it's block quoted

**Comment by AndreLouisIssa** [comment]
Failing that, yeah I guess you could revert and we'll try making a PR later which you can test still meets the rest of the features of the module

**Comment by Anteru** [comment]
I'm not following: With the latest commit, a multi-line, triple-quoted string remains multi-line. If that's not helping anyone, I'd rather remove triple-quoted strings, but I don't follow your statement about multi-line -- I've even checked in a test case for it: https://github.com/Anteru/sjson/blob/5e0c0b61c9446187649df8c728af7308dd40fc8a/sjson/test/test_sjson.py#L332 and according to that, multi-line strings remain multi-line strings.

**Comment by AndreLouisIssa** [comment]
Alright, I'll test it

**Comment by AndreLouisIssa** [comment]
So again, program runs, but the game errors on reading data.
It might have something to do with encoding

**Comment by AndreLouisIssa** [comment]
Oh I see, the output doesn't place the (usually implicit) { and } over it
But fixing that manually does not make it readable still.

**Comment by AndreLouisIssa** [comment]
Since the issues seem to lie with the game, it's our responsibility to fix that (and we can with wrappers or using our current local version)
But I think adding support for tripple quotes is still gonna be useful for other applications. And you've tested that your output is fine subject to all the normal assumptions you can make.

Is there any reason why [=[ was chosen for block quotes originally?
That the devs of this game decided to use tripple quotes implies to me that sjson has no standard for block quotes (at least not  established prior to 2018)

**Comment by Anteru** [comment]
Yes, the main reason to choose [=[ was to match Lua and have an easier time parsing it than """ :) The advantage is that it only requires finding ]=] to terminate the search, while """ is "harder" in the sense that it requires more lookahead (and given SJSON doesn't use a tokenizing parser ...)

SJSON is not specified at all, so everything goes, when I added raw strings back in the day I picked the easiest variant. In any case, I'm going to keep the triple-quotes as-is now and prepare a new release with it.
